const $=s=>document.querySelector(s);let current=null;let pollTimer=null;
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const t=await r.text();let data;try{data=JSON.parse(t)}catch{data={error:t}}if(!r.ok)throw new Error(data.error||r.statusText);return data}
function badge(text,ok){return `<span class="badge" style="border-color:${ok?'#3c8':'#a66'}">${text}</span>`}
async function loadSystem(){try{const s=await api('/api/status');$('#systemBadges').innerHTML=badge(`Python ${s.python}`,true)+badge(s.git?'Git':'Git missing',s.git)+badge(s.codex?`Codex ${s.codex_version||''}`:'Codex missing',s.codex)+badge(s.opencv&&s.mss?'OpenCV ready':'OpenCV deps missing',s.opencv&&s.mss)}catch(e){$('#systemBadges').textContent=e.message}}
async function loadProjects(selectId=null){const d=await api('/api/projects');const list=$('#projectList');list.innerHTML='';for(const p of d.projects){const b=document.createElement('button');b.className='project-item'+((current===p.id)?' active':'');b.innerHTML=`<strong>${esc(p.name)}</strong><small>${esc(p.agent_status.status||'idle')} • iteration ${p.agent_status.iteration||0}</small>`;b.onclick=()=>selectProject(p.id);list.appendChild(b)}if(selectId)await selectProject(selectId)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function selectProject(id){current=id;$('#emptyState').hidden=true;$('#workspace').hidden=false;await refreshState();await loadProjects();clearInterval(pollTimer);pollTimer=setInterval(refreshState,1800)}
async function refreshState(){if(!current)return;try{const d=await api(`/api/project/${current}/state`);const c=d.config;$('#projectTitle').textContent=c.name;$('#projectGoal').textContent=c.goal;$('#agentBadge').textContent=`Agent: ${d.agent.status}`;$('#iterationBadge').textContent=`Iteration ${d.agent.iteration||0}`;$('#agentMessage').textContent=d.agent.message||d.agent.status;$('#cvMessage').textContent=d.cv.message||d.cv.status;$('#researchMode').value=c.research_mode||'deep';$('#internetResearch').checked=!!c.internet_research;$('#buildCmd').value=c.commands?.build||'';$('#testCmd').value=c.commands?.test||'';$('#launchCmd').value=c.commands?.launch||'';$('#monitorNum').value=c.visual?.monitor??1;$('#freezeSeconds').value=c.visual?.freeze_seconds??8;renderAcceptance(d.acceptance);renderUploads(d.uploads);$('#visualMetrics').textContent=Object.keys(d.visual||{}).length?JSON.stringify(d.visual,null,2):'No visual metrics yet.';if(d.visual?.timestamp){const img=$('#capture');img.hidden=false;img.src=`/api/project/${current}/capture.jpg?t=${Date.now()}`}else $('#capture').hidden=true}catch(e){console.error(e)}}
function renderAcceptance(a){const box=$('#acceptance');box.innerHTML=`<p><strong>Project complete:</strong> ${a?.project_complete?'YES':'Not yet'}</p>`+(a?.criteria||[]).map(c=>`<div class="criterion ${c.status==='pass'?'pass':'pending'}"><strong>${esc(c.id)}</strong> — ${esc(c.description)}<br><small>${esc(c.status)}${c.evidence?` • ${esc(c.evidence)}`:''}</small></div>`).join('')}
function renderUploads(u){$('#uploadList').innerHTML=`<p>${u?.count||0} scanned items</p>`+(u?.items||[]).slice(0,100).map(x=>`<div class="criterion"><strong>${esc(x.path)}</strong><br><small>${x.bytes||0} bytes • ${esc(x.sha256||x.error||'')}</small></div>`).join('')}
async function postAction(action,body={}){if(!current)return;return api(`/api/project/${current}/${action}`,{method:'POST',body:JSON.stringify(body)})}
$('#createBtn').onclick=async()=>{const goal=$('#newGoal').value.trim();if(!goal)return alert('Describe the playable result first.');try{const p=await api('/api/projects/create',{method:'POST',body:JSON.stringify({name:$('#newName').value||'Game Project',goal,research_mode:$('#newResearch').value})});$('#newGoal').value='';await loadProjects(p.id)}catch(e){alert(e.message)}};
$('#refreshBtn').onclick=()=>loadProjects();
for(const [id,act] of [['startAgent','agent/start'],['pauseAgent','agent/pause'],['resumeAgent','agent/resume'],['stopAgent','agent/stop'],['startCv','cv/start'],['stopCv','cv/stop']])$('#'+id).onclick=async()=>{try{await postAction(act);await refreshState()}catch(e){alert(e.message)}};
async function run(which){$('#runOutput').textContent=`Running ${which}...`;try{const r=await postAction(`run/${which}`);$('#runOutput').textContent=(r.output||'')+`\nexit=${r.exit_code} ok=${r.ok}`}catch(e){$('#runOutput').textContent=e.message}}
$('#runBuild').onclick=()=>run('build');$('#runTest').onclick=()=>run('test');$('#runLaunch').onclick=()=>run('launch');
$('#checkpoint').onclick=async()=>{try{const r=await postAction('git/checkpoint',{message:'GameForge manual checkpoint'});$('#runOutput').textContent=JSON.stringify(r,null,2)}catch(e){alert(e.message)}};
$('#saveSettings').onclick=async()=>{try{await postAction('config',{research_mode:$('#researchMode').value,internet_research:$('#internetResearch').checked,commands:{build:$('#buildCmd').value,test:$('#testCmd').value,launch:$('#launchCmd').value},visual:{monitor:Number($('#monitorNum').value)||1,interval_sec:1,freeze_seconds:Number($('#freezeSeconds').value)||8,black_mean_threshold:8,region:null,window_title:$('#windowTitle').value}});await refreshState();alert('Saved')}catch(e){alert(e.message)}};
$('#scanUploads').onclick=async()=>{try{const r=await postAction('uploads/scan');renderUploads(r)}catch(e){alert(e.message)}};
$('#uploadBtn').onclick=async()=>{if(!current)return;const files=[...$('#uploadFiles').files];if(!files.length)return alert('Select files.');const cat=$('#uploadCategory').value;for(let i=0;i<files.length;i++){const f=files[i];$('#uploadStatus').textContent=`Uploading ${i+1}/${files.length}: ${f.name}`;const r=await fetch(`/api/project/${current}/upload?category=${encodeURIComponent(cat)}&path=${encodeURIComponent(f.webkitRelativePath||f.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':f.name},body:f});if(!r.ok)throw new Error(await r.text())}$('#uploadStatus').textContent='Upload complete. Scanning…';const m=await postAction('uploads/scan');renderUploads(m);$('#uploadStatus').textContent='Upload intake complete.'};
$('#refreshLogs').onclick=async()=>{if(!current)return;try{const d=await api(`/api/project/${current}/logs`);$('#logs').innerHTML=d.files.map(f=>`<details class="logbox"><summary>${esc(f.name)}</summary><pre>${esc(f.text)}</pre></details>`).join('')||'<p>No logs yet.</p>'}catch(e){alert(e.message)}};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active')});
loadSystem();
const requestedProject=new URLSearchParams(location.search).get('project');
loadProjects(requestedProject);

$('#runResearch').onclick=async()=>{if(!current)return;$('#researchOutput').textContent='Researching…';try{const r=await postAction('research/run',{question:$('#researchQuestion').value||'Research whatever is currently most important to completing the playable game goal professionally.'});$('#researchOutput').textContent=r.output||JSON.stringify(r,null,2)}catch(e){$('#researchOutput').textContent=e.message}};
$('#managedLaunch').onclick=async()=>{try{const r=await postAction('process/start',{});$('#processStatus').textContent=JSON.stringify(r,null,2);await refreshState()}catch(e){alert(e.message)}};
$('#managedStop').onclick=async()=>{try{const r=await postAction('process/stop',{});$('#processStatus').textContent=JSON.stringify(r,null,2);await refreshState()}catch(e){alert(e.message)}};
$('#refreshProcesses').onclick=async()=>{if(!current)return;try{const r=await api(`/api/project/${current}/processes`);$('#processList').textContent=r.processes.slice(0,120).map(p=>`${p.pid}\t${p.name}\t${p.exe}`).join('\n')}catch(e){$('#processList').textContent=e.message}};
$('#runInput').onclick=async()=>{try{const seq=JSON.parse($('#inputSequence').value);const r=await postAction('input/replay',{sequence:seq});$('#inputOutput').textContent=JSON.stringify(r,null,2)}catch(e){$('#inputOutput').textContent=e.message}};
$('#analyzeAssets').onclick=async()=>{try{const r=await postAction('assets/analyze',{});$('#assetOutput').textContent=JSON.stringify(r,null,2)}catch(e){$('#assetOutput').textContent=e.message}};
$('#gitStatusBtn').onclick=async()=>{try{const r=await postAction('git/status',{});$('#gitOutput').textContent=`HEAD ${r.head||''}\n\n${r.status||''}\n${r.log||''}`}catch(e){$('#gitOutput').textContent=e.message}};
$('#rollbackBtn').onclick=async()=>{const rev=$('#rollbackRev').value.trim();if(!rev)return alert('Enter a commit hash.');if(!confirm(`Hard-reset this project to ${rev}? A safety checkpoint will be attempted first.`))return;try{const r=await postAction('git/rollback',{revision:rev});$('#gitOutput').textContent=JSON.stringify(r,null,2);await refreshState()}catch(e){$('#gitOutput').textContent=e.message}};
